JoshuaKGoldberg/intern-assassins

package.json, src/server/api.ts, src/server/endpoints/killclaimsendpoint.ts, src/server/endpoints/notificationsendpoint.ts, src/server/server.ts, src/server/sockets.ts, src/shared/notifications.ts, src/site/scripts/components/apps/app.tsx, src/site/scripts/components/apps/appuser.tsx, src/site/scripts/components/sidebar/activity.tsx, src/site/scripts/components/sidebar/activityboard.tsx, src/site/scripts/components/sidebar/sidebar.tsx, src/site/styles/theme.less, tsconfig.json
They also now show in the activity bar with their timestamp.
Fixes #75.
Fixes #76.
=> Changed notifications to be a complex type

.travis.yml, README.md, src/server/endpoints/killclaimsendpoint.ts
They work but don't yet run feature tests. 
Fixes #79.
Opens #85.
=> Added .travis.yml for Travis builds

src/server/endpoints/notificationsendpoint.ts, src/server/sockets.ts, src/shared/users.ts, src/site/scripts/components/apps/app.tsx, src/site/scripts/sdk/sdk.ts
Added a GET route to the notifications endpoint and used it in `app.tsx` to populate the activity bar.
Fixes #33.
=> Notifications history in activity bar

Contributing.md
=> Contributing guide

src/site/scripts/components/apps/app.tsx, src/site/scripts/components/apps/appadmin.tsx, src/site/scripts/components/apps/appuser.tsx
=> Added sidebar to admin page

assassins.default.json, src/server/endpoints/usersendpoint.ts, src/shared/users.ts, src/site/scripts/components/apps/appadmin.tsx, src/site/scripts/components/profile/infodisplay.tsx, src/site/scripts/components/profile/profile.tsx
Also, nickname needs to be a non-editable field. Users shouldn't be able
to edit their profiles.
Fixes #100 .
=> Removed the "biography" field from users

package.json, src/server/endpoints/usersendpoint.ts, src/site/scripts/components/admin/usersimporter.tsx, src/site/scripts/components/admin/userstable.tsx, src/site/scripts/components/admin/userstables.tsx, src/site/scripts/components/apps/appadmin.tsx, src/site/scripts/components/apps/appuser.tsx, src/site/scripts/components/profile/actionbutton.tsx, src/site/scripts/index.ts, src/site/scripts/sdk/sdk.ts, src/site/scripts/storage/sheetparser.ts, src/site/styles/layout.less, tsconfig.json, typings/jszip/index.d.ts, typings/react-dropzone/index.d.ts, typings/xlsx/index.d.ts
Admin page now has a button to import a .xlsx of users.
Fixes #104.
=> Admin-only .xlsx importing

.eslintrc.json, gulpfile.js, package.json, test/integration/steps/kills.js, test/integration/steps/leaders.js, test/integration/steps/login.js, test/integration/steps/steps.js, test/integration/steps/users.js, test/integration/support/hooks.js, test/integration/support/kills.js, test/integration/support/leaders.js, test/integration/support/login.js, test/integration/support/testmongodb.js, test/integration/support/testserver.js, test/integration/support/users.js, test/integration/support/world.js
=> Added eslint for .js test files

assassins.default.json, src/server/endpoints/claimsendpoint.ts, src/server/endpoints/killsendpoint.ts, src/server/endpoints/leadersendpoint.ts, src/server/endpoints/loginendpoint.ts, src/server/endpoints/usersendpoint.ts, src/server/notifications/emailnotifier.ts, src/shared/login.ts, src/shared/notifications.ts, src/shared/users.ts, src/site/scripts/components/admin/usersimporter.tsx, src/site/scripts/components/admin/userstables.tsx, src/site/scripts/components/apps/app.tsx, src/site/scripts/components/apps/appadmin.tsx, src/site/scripts/components/apps/appanonymous.tsx, src/site/scripts/components/profile/greeting.tsx, src/site/scripts/components/profile/profile.tsx, src/site/scripts/components/sidebar/leaderboard.tsx, src/site/scripts/storage/appstorage.ts, src/site/scripts/storage/sheetparser.ts, test/integration/support/claims.js, test/integration/support/leaders.js, test/integration/support/users.js, test/integration/support/world.js
For the most part, a simple case-sensitive find-and-replace.
Fixes #118.
=> Renamed "nickname" to "codename"

src/site/scripts/components/footer.tsx, src/site/scripts/components/profile/actionbutton.tsx
#8 - Adds a cancel button for the confirmation.
Also sneaking #35
=> Cancel for action button

src/site/scripts/components/apps/app.tsx, src/site/scripts/components/apps/appadmin.tsx, src/site/scripts/components/apps/appanonymous.tsx, src/site/scripts/components/apps/appuser.tsx, src/site/scripts/components/sidebar/countdown.tsx, src/site/scripts/components/sidebar/sidebar.tsx, src/site/styles/theme.less, tsconfig.json
It shows the time remaining in the current round with a general
`Countdown` component, which `AppAnonymous` now uses for its countdown.
Fixes #122.
=> Added a rounds countdown timer to the sidebar

src/site/styles/theme.less
Fixes a CSS glitch where the whole body has a vertical scrollbar even
though it doesn't need one.
=> White background, better padding in app-countdown

src/site/scripts/components/sidebar/sidebar.tsx
=> Removed unnecessary log in sidebar.tsx

package.json, src/site/scripts/storage/sheetparser.ts
All but the last row of an alias will be used, and duplicate codenames will have a (#) appended.
Fixes #108.
=> Restricted admin imports

src/server/endpoints/leadersendpoint.ts, src/site/scripts/components/apps/app.tsx, src/site/scripts/components/sidebar/leaderboard.tsx, src/site/styles/theme.less
=> Limited leaders to 15

src/site/scripts/components/apps/appuser.tsx, src/site/scripts/components/profile/actionbutton.tsx, src/site/scripts/components/profile/actions.tsx, src/site/scripts/components/profile/confirmationdialog.tsx, src/site/scripts/components/profile/profile.tsx, src/site/styles/layout.less, src/site/styles/theme.less, src/site/styles/variables.less, tsconfig.json
Messed up PR #145 -- this is with merged changes from master.
=> Bug fix/remove countdown (fixed PR)

src/site/scripts/components/apps/appadmin.tsx
=> Changed admin signout to standard "sign out"

src/site/scripts/components/admin/userstable.tsx, src/site/scripts/components/admin/userstables.tsx, src/site/styles/theme.less, src/site/styles/variables.less
Also allowed all fields (excluding aliases) to be edited.
Fixes #172.
=> Added passwords to user tables

src/site/scripts/sdk/sdk.ts
=> Encoded URI component bodies for GET requests

src/server/endpoints/claimsendpoint.ts, src/shared/kills.ts, src/site/scripts/components/admin/claimstable.tsx, src/site/scripts/components/admin/userstable.tsx, src/site/scripts/sdk/sdk.ts
=> Added admin Approve and Deny buttons to claims

src/server/endpoints/usersendpoint.ts, src/site/scripts/components/admin/userstable.tsx, src/site/scripts/components/admin/userstables.tsx, src/site/scripts/sdk/sdk.ts, src/site/styles/layout.less
This bypasses the "pending changes" idea of the admin table.
Fixes #105.
=> Added an "Kill Quietly" admin button for users

src/server/endpoints/leadersendpoint.ts, src/site/scripts/components/admin/userstable.tsx, src/site/scripts/sdk/sdk.ts, src/site/styles/layout.less
Also standardized the displays of the activity feed vs leaderboard so it
doesn't look weird having the scrollbar shift around.
Fixes #179.
=> Switched 15-leader-limit with overflow-y scrolling

src/shared/users.ts, src/site/scripts/components/admin/userfield.tsx, src/site/scripts/components/admin/userstable.tsx, src/site/scripts/components/admin/userstables.tsx, src/site/styles/layout.less
Also shrunk & standardized inputs in the admin table.
Fixes #180.
=> Added support for numeric user fields
